export const OPEN_CLOSE_CART = 'OPEN_CLOSE_CART'
export type OPEN_CLOSE_CART = typeof OPEN_CLOSE_CART

export const UPDATE_CART = 'UPDATE_CART'
export type UPDATE_CART = typeof UPDATE_CART

export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export type REMOVE_ITEM_CART = typeof REMOVE_ITEM_CART

export const CHECKOUT_CART = 'CHECKOUT_CART'
export type CHECKOUT_CART = typeof CHECKOUT_CART