export const RETRIEVE_POKEMON_DATA = 'RETRIEVE_POKEMON_DATA'
export type RETRIEVE_POKEMON_DATA = typeof RETRIEVE_POKEMON_DATA

export const GET_POKEMON_DATA = 'GET_POKEMON_DATA'
export type GET_POKEMON_DATA = typeof GET_POKEMON_DATA

export const SET_LOADING_DATA = 'SET_LOADING_DATA'
export type SET_LOADING_DATA = typeof SET_LOADING_DATA

export const UPDATE_PAGE = 'UPDATE_PAGE'
export type UPDATE_PAGE = typeof UPDATE_PAGE