export const RETRIEVE_POKEMON_DATA = 'RETRIEVE_POKEMON_DATA'
export type RETRIEVE_POKEMON_DATA = typeof RETRIEVE_POKEMON_DATA
export const GET_POKEMON_DATA = 'GET_POKEMON_DATA'
export type GET_POKEMON_DATA = typeof GET_POKEMON_DATA